stages:
  - stage: 'code_quality'
    displayName: 'Code Quality Checks'

    jobs:
      - job: 'python_checks'
        displayName: 'Python Checks'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
          - bash: pip install flake8 yapf==0.30.0
            displayName: 'Install tooling'
          - bash: |
              set -ex
              flake8 --version
              # Perform format checking on all Python files
              find . -type f -name '*.py' | xargs flake8
            displayName: 'Run flake8'
          - bash: |
              set -ex
              yapf --version
              # Perform format checking on all Python API files
              yapf --diff --recursive .
            displayName: 'Run yapf'
