trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_release: $[eq(variables['System.PullRequest.TargetBranch'], 'release')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:
  - template: code_quality_checks.yml
  - stage: 'test'
    displayName: 'Python tests'

    jobs:
      - job: 'python_test'
        displayName: 'Python tests'
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          - bash: |
             set -ex
             echo is main $(is_release)
             echo target branch $(System.PullRequest.TargetBranch)
             # If release use release scipp version from scipp channel, otherwise use scipp/label/dev channel
             conda config --set always_yes yes --set changeps1 no
             if [ $(is_release) == False ]; then
                 conda env create -f scippneutron-latest.yml
                 source activate scippneutron-latest
             else
                 conda env create -f scippneutron.yml
                 source activate scippneutron
             fi
             python -m pytest --junitxml=junit/unit-test.xml
            displayName: 'run pytest'
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: 'junit/*.xml'
            condition: succeededOrFailed()
  - stage: 'post_build_checks'
    displayName: 'Post Build Checks'

    jobs:
      - template: documentation_build.yml
